### ISSUE TITLE
Using Guzzle instead of file_get_contents

### ISSUE THREAD

**Issue by jcolfej** [JustAuthMe/PHP-SDK#1]
Currently, the SDK uses `file_get_contents` to call the JustAuthMe API.

For security reasons, `file_get_contents` may not be allowed to call remote URL.
Also, `file_get_contents` is often slower than Curl.

Guzzle allows you to manage multiple handlers: https://github.com/guzzle/guzzle/blob/master/src/Utils.php#L81-L102

This would make the SDK easier to use on more environments, right?

**Comment by p-cauty** [comment]
Hi,
As far as I know, calling HTTPS remote URLs with `file_get_contents` was an issue before PHP 5.6, as TLS/SSL was disabled by default. Because this SDK require PHP >= 7.1, this shouldn't be an issue, but maybe I'm wrong. If you have further infos to that effect, please let me know.

However, regarding the second issue you posted, we will consider cURL. Guzzle is not something that we want to look into because we prefer to have a SDK as lightweight as possible.

**Comment by jcolfej** [comment]
Hello ;)

By "For security reasons, `file_get_contents` may not be allowed to call remote URL.", I meant that many hosts disable the ability to use `file_get_contents` with remote URL.
https://www.php.net/manual/en/filesystem.configuration.php#ini.allow-url-fopen

The advantage of Guzzle is that it uses Curl if possible, and if not, it tries with `file_get_contents`, and if nothing works it throws an exception.

Maybe it would be interesting to implement this to be as compatible as possible.

**Comment by p-cauty** [comment]
I understand, thank you for your suggestion :) We'll look into it!
